// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCIYQoL62QF_B4NnsZ51cDKJpF5q1Xlxw4',
    appId: '1:26703591720:web:78238350375fc64c51381d',
    messagingSenderId: '26703591720',
    projectId: 'finalyearproj-88e7c',
    authDomain: 'finalyearproj-88e7c.firebaseapp.com',
    storageBucket: 'finalyearproj-88e7c.firebasestorage.app',
    measurementId: 'G-9WG1GEPWKP',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCasvz8y7ko9P0cOZt0hu_Ox5FwyeThyng',
    appId: '1:26703591720:android:2ab06811c6e5fd2b51381d',
    messagingSenderId: '26703591720',
    projectId: 'finalyearproj-88e7c',
    storageBucket: 'finalyearproj-88e7c.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyATOpByQzLTMHgAWiDLba-GI_xQv--Uj4k',
    appId: '1:26703591720:ios:b8314259b48e7d1651381d',
    messagingSenderId: '26703591720',
    projectId: 'finalyearproj-88e7c',
    storageBucket: 'finalyearproj-88e7c.firebasestorage.app',
    iosBundleId: 'com.example.fyp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyATOpByQzLTMHgAWiDLba-GI_xQv--Uj4k',
    appId: '1:26703591720:ios:b8314259b48e7d1651381d',
    messagingSenderId: '26703591720',
    projectId: 'finalyearproj-88e7c',
    storageBucket: 'finalyearproj-88e7c.firebasestorage.app',
    iosBundleId: 'com.example.fyp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCIYQoL62QF_B4NnsZ51cDKJpF5q1Xlxw4',
    appId: '1:26703591720:web:eff96cdf68e530f451381d',
    messagingSenderId: '26703591720',
    projectId: 'finalyearproj-88e7c',
    authDomain: 'finalyearproj-88e7c.firebaseapp.com',
    storageBucket: 'finalyearproj-88e7c.firebasestorage.app',
    measurementId: 'G-KPLJW9EZ5P',
  );
}
